# Dockerfile for LIMO Cobot Simulation with ROS 2 Humble


# Base image with ROS 2 Humble
FROM osrf/ros:humble-desktop


# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ARG USERNAME=ros
ENV USERNAME=$USERNAME


# Create a non-root user
RUN useradd -ms /bin/bash $USERNAME && \
echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME


# Install basic tools and ROS build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
sudo \
build-essential \
git \
wget \
curl \
lsb-release \
gnupg2 \
nano \
python3-colcon-common-extensions \
python3-pip \
python3-rosdep \
python3-vcstool && \
rm -rf /var/lib/apt/lists/*


# Initialize rosdep
RUN rosdep init || true
RUN rosdep update


# Create workspace and change to working directory
WORKDIR /home/$USERNAME/limo_cobot_ws/src


# Clone required repos
RUN git clone -b humble --depth 1 https://github.com/agilexrobotics/limo_ros2.git && \
git clone --depth 1 https://github.com/agilexrobotics/limo_cobot_sim.git && \
git clone --depth 1 https://github.com/elephantrobotics/mycobot_ros2.git


# Remove conflicting duplicated packages
RUN rm -rf \
/home/$USERNAME/limo_cobot_ws/src/limo_ros2/limo_description \
/home/$USERNAME/limo_cobot_ws/src/mycobot_ros2/mycobot_description \
/home/$USERNAME/limo_cobot_ws/src/limo_cobot_sim/limo_mycobot/mycobot_description \
/home/$USERNAME/limo_cobot_ws/src/limo_cobot_sim/limo_mycobot/limo/limo_description


# Install ROS 2 and simulation-related dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
ros-humble-joint-state-publisher-gui \
ros-humble-gazebo-ros-pkgs \
ros-humble-xacro \
ros-humble-rviz2 \
ros-humble-robot-state-publisher && \
rm -rf /var/lib/apt/lists/*


# Set workdir for dependency installation
WORKDIR /home/$USERNAME/limo_cobot_ws


# Install dependencies with rosdep
RUN /bin/bash -lc "source /opt/ros/humble/setup.bash && \
rosdep update && \
rosdep install --from-paths src --ignore-src -r -y"


# Build the workspace
RUN /bin/bash -lc "source /opt/ros/humble/setup.bash && \
colcon build"


# Set default user
USER $USERNAME


# Source the ROS setup by default
RUN echo 'source /opt/ros/humble/setup.bash' >> /home/$USERNAME/.bashrc && \
echo 'source /home/$USERNAME/limo_cobot_ws/install/setup.bash' >> /home/$USERNAME/.bashrc


WORKDIR /home/$USERNAME/limo_cobot_ws